server:
  port: 8883 #端口号

spring:
  application:
    name: service-user #应用名称
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.216.201:8848 #nacos 配置注册中心
    sentinel:
      transport:
        dashboard: 192.168.216.201:8080 #sentinel dashborad 地址
        port: 8719 #客户端ip
        heartbeat-interval-ms: 1000 #发送心跳时间间隔
      eager: true

feign:
  sentinel:
    enabled: true #开启feign对sentinel的支持

