server:
  port: 8885
spring:
  application:
    name: service-system

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.216.201:8848
    sentinel:
      transport:
        dashboard: 192.168.216.201:8080
        port: 8730
        heartbeat-interval-ms: 1000
      eager: true
